-- Insert 100 posts with unique content
INSERT OR IGNORE INTO post (id, user_id, title, data) 
VALUES 
(1, 1, 'Welcome to our community', 'This is our first general discussion post. Feel free to introduce yourself!'),
(2, 1, 'Tips for new members', 'Here are some helpful guidelines for participating in our community...'),
(3, 1, 'Weekly discussion thread', 'Share your thoughts and experiences from this week...'),
(4, 1, 'Important announcements', 'Stay updated with our latest community updates and news...'),
(5, 1, 'Feature suggestions', 'What features would you like to see added to our platform?'),
(6, 1, 'Community spotlight', 'Highlighting some of our most active community members...'),
(7, 1, 'Monthly recap', 'Here''s what happened in our community this month...'),
(8, 1, 'Frequently asked questions', 'Common questions and their answers for quick reference...'),
(9, 1, 'Feedback thread', 'Share your thoughts on how we can improve the community...'),
(10, 1, 'General discussion', 'Open thread for any topic you''d like to discuss...'),
(11, 1, 'Post 11 Title', 'This is the content for post 11...'),
(12, 1, 'Post 12 Title', 'This is the content for post 12...'),
(13, 1, 'Post 13 Title', 'This is the content for post 13...'),
(14, 1, 'Post 14 Title', 'This is the content for post 14...'),
(15, 1, 'Post 15 Title', 'This is the content for post 15...'),
(16, 1, 'Post 16 Title', 'This is the content for post 16...'),
(17, 1, 'Post 17 Title', 'This is the content for post 17...'),
(18, 1, 'Post 18 Title', 'This is the content for post 18...'),
(19, 1, 'Post 19 Title', 'This is the content for post 19...'),
(20, 1, 'Post 20 Title', 'This is the content for post 20...'),
(21, 1, 'Post 21 Title', 'This is the content for post 21...'),
(22, 1, 'Post 22 Title', 'This is the content for post 22...'),
(23, 1, 'Post 23 Title', 'This is the content for post 23...'),
(24, 1, 'Post 24 Title', 'This is the content for post 24...'),
(25, 1, 'Post 25 Title', 'This is the content for post 25...'),
(26, 1, 'Post 26 Title', 'This is the content for post 26...'),
(27, 1, 'Post 27 Title', 'This is the content for post 27...'),
(28, 1, 'Post 28 Title', 'This is the content for post 28...'),
(29, 1, 'Post 29 Title', 'This is the content for post 29...'),
(30, 1, 'Post 30 Title', 'This is the content for post 30...'),
(31, 1, 'Post 31 Title', 'This is the content for post 31...'),
(32, 1, 'Post 32 Title', 'This is the content for post 32...'),
(33, 1, 'Post 33 Title', 'This is the content for post 33...'),
(34, 1, 'Post 34 Title', 'This is the content for post 34...'),
(35, 1, 'Post 35 Title', 'This is the content for post 35...'),
(36, 1, 'Post 36 Title', 'This is the content for post 36...'),
(37, 1, 'Post 37 Title', 'This is the content for post 37...'),
(38, 1, 'Post 38 Title', 'This is the content for post 38...'),
(39, 1, 'Post 39 Title', 'This is the content for post 39...'),
(40, 1, 'Post 40 Title', 'This is the content for post 40...'),
(41, 1, 'Post 41 Title', 'This is the content for post 41...'),
(42, 1, 'Post 42 Title', 'This is the content for post 42...'),
(43, 1, 'Post 43 Title', 'This is the content for post 43...'),
(44, 1, 'Post 44 Title', 'This is the content for post 44...'),
(45, 1, 'Post 45 Title', 'This is the content for post 45...'),
(46, 1, 'Post 46 Title', 'This is the content for post 46...'),
(47, 1, 'Post 47 Title', 'This is the content for post 47...'),
(48, 1, 'Post 48 Title', 'This is the content for post 48...'),
(49, 1, 'Post 49 Title', 'This is the content for post 49...'),
(50, 1, 'Post 50 Title', 'This is the content for post 50...'),
(51, 1, 'Post 51 Title', 'This is the content for post 51...'),
(52, 1, 'Post 52 Title', 'This is the content for post 52...'),
(53, 1, 'Post 53 Title', 'This is the content for post 53...'),
(54, 1, 'Post 54 Title', 'This is the content for post 54...'),
(55, 1, 'Post 55 Title', 'This is the content for post 55...'),
(56, 1, 'Post 56 Title', 'This is the content for post 56...'),
(57, 1, 'Post 57 Title', 'This is the content for post 57...'),
(58, 1, 'Post 58 Title', 'This is the content for post 58...'),
(59, 1, 'Post 59 Title', 'This is the content for post 59...'),
(60, 1, 'Post 60 Title', 'This is the content for post 60...'),
(61, 1, 'Post 61 Title', 'This is the content for post 61...'),
(62, 1, 'Post 62 Title', 'This is the content for post 62...'),
(63, 1, 'Post 63 Title', 'This is the content for post 63...'),
(64, 1, 'Post 64 Title', 'This is the content for post 64...'),
(65, 1, 'Post 65 Title', 'This is the content for post 65...'),
(66, 1, 'Post 66 Title', 'This is the content for post 66...'),
(67, 1, 'Post 67 Title', 'This is the content for post 67...'),
(68, 1, 'Post 68 Title', 'This is the content for post 68...'),
(69, 1, 'Post 69 Title', 'This is the content for post 69...'),
(70, 1, 'Post 70 Title', 'This is the content for post 70...'),
(71, 1, 'Post 71 Title', 'This is the content for post 71...'),
(72, 1, 'Post 72 Title', 'This is the content for post 72...'),
(73, 1, 'Post 73 Title', 'This is the content for post 73...'),
(74, 1, 'Post 74 Title', 'This is the content for post 74...'),
(75, 1, 'Post 75 Title', 'This is the content for post 75...'),
(76, 1, 'Post 76 Title', 'This is the content for post 76...'),
(77, 1, 'Post 77 Title', 'This is the content for post 77...'),
(78, 1, 'Post 78 Title', 'This is the content for post 78...'),
(79, 1, 'Post 79 Title', 'This is the content for post 79...'),
(80, 1, 'Post 80 Title', 'This is the content for post 80...'),
(81, 1, 'Post 81 Title', 'This is the content for post 81...'),
(82, 1, 'Post 82 Title', 'This is the content for post 82...'),
(83, 1, 'Post 83 Title', 'This is the content for post 83...'),
(84, 1, 'Post 84 Title', 'This is the content for post 84...'),
(85, 1, 'Post 85 Title', 'This is the content for post 85...'),
(86, 1, 'Post 86 Title', 'This is the content for post 86...'),
(87, 1, 'Post 87 Title', 'This is the content for post 87...'),
(88, 1, 'Post 88 Title', 'This is the content for post 88...'),
(89, 1, 'Post 89 Title', 'This is the content for post 89...'),
(90, 1, 'Post 90 Title', 'This is the content for post 90...'),
(91, 1, 'Post 91 Title', 'This is the content for post 91...'),
(92, 1, 'Post 92 Title', 'This is the content for post 92...'),
(93, 1, 'Post 93 Title', 'This is the content for post 93...'),
(94, 1, 'Post 94 Title', 'This is the content for post 94...'),
(95, 1, 'Post 95 Title', 'This is the content for post 95...'),
(96, 1, 'Post 96 Title', 'This is the content for post 96...'),
(97, 1, 'Post 97 Title', 'This is the content for post 97...'),
(98, 1, 'Post 98 Title', 'This is the content for post 98...'),
(99, 1, 'Post 99 Title', 'This is the content for post 99...'),
(100, 1, 'Post 100 Title', 'This is the content for post 100...');


